package quizz.views;

public enum MenuCommand {
	NONE,
	EXIT,
	SAVE,
	LIST_ALL_ADMINS, LIST_ALL_PLAYERS, LIST_ALL_QUESTIONS, LIST_ALL_ANSWERS, LIST_ALL_QUIZZES,
	ADD_ADMIN, ADD_PLAYER, ADD_QUESTION, ADD_ANSWER, ADD_QUIZ,
	UPDATE_PLAYER_BY_ID, UPDATE_ADMIN_BY_ID, UPDATE_QUESTION_BY_ID, UPDATE_ANSWER_BY_ID, UPDATE_QUIZ_BY_ID,
	DELETE_PLAYER_BY_ID, DELETE_ADMIN_BY_ID, DELETE_QUESTION_BY_ID, DELETE_ANSWER_BY_ID, DELETE_QUIZ_BY_ID,

}
